#Healthcecks
x-spring-healthcheck: &spring-healthcheck
  test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
  interval: 20s
  timeout: 3s
  retries: 5
x-redis-healthcheck: &redis-healthcheck
  test: [ "CMD", "redis-cli", "ping" ]
  interval: 20s
  timeout: 5s
  retries: 5
x-neo4j-healthcheck: &neo4j-healthcheck
  test:
    wget http://localhost:7474 || exit 1
  interval: 20s
  timeout: 5s
  retries: 5
x-pg-healthcheck: &pg-healthcheck
  test: [ "CMD-SHELL", "pg_isready" ]
  interval: 20s
  timeout: 5s
  retries: 5
  start_period: 15s


services:
  # Main Services
  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    image: api-gateway:latest
    container_name: beacon-api-gateway
    ports:
      - "8080:8080"
      - "9292:9292"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
    healthcheck: *spring-healthcheck
    profiles: [ services ]
  
  service-registry:
    build:
      context: .
      args:
        SERVICE_NAME: service-registry
        SERVICE_PORT: 8761
    image: service-registry:latest
    container_name: beacon-service-registry
    ports:
      - "8761:8761"
    environment:
      JAVA_OPTS:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    profiles: [ services ]

  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    image: auth-service:latest
    container_name: beacon-auth-service
    ports:
      - "8082:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      GRPC_PORT: 9090
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      GRPC_USER_CHANNEL_URL: user-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  location-service:
    build:
      context: .
      args:
        SERVICE_NAME: location-service
    image: location-service:latest
    container_name: beacon-location-service
    ports:
      - "8083:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      KAFKA_URL: kafka:9093
      REDIS_HOST: location-redis
      REDIS_PORT: 6379
      GRPC_PORT: 9090
      GRPC_USER_CHANNEL_URL: user-service:9090
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      location-redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck
  
  map-service:
    build:
      context: .
      args:
        SERVICE_NAME: map-service
    image: map-service:latest
    container_name: beacon-map-service
    ports:
      - "8084:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      KAFKA_URL: kafka:9093
      REDIS_HOST: map-redis
      REDIS_PORT: 6379
      GRPC_USER_CHANNEL_URL: user-service:9090
      GRPC_LOCATION_CHANNEL_URL: location-service:9090
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      map-redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    image: user-service:latest
    container_name: beacon-user-service
    ports:
      - "8085:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      NEO4J_URI: bolt://user-db:7687
      KAFKA_URL: kafka:9093
      GRPC_PORT: 9090
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  history-service:
    build:
      context: .
      args:
        SERVICE_NAME: history-service
    image: history-service:latest
    container_name: beacon-history-service
    ports:
      - "8086:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      DB_URL: jdbc:postgresql://history-db:5432/history_db
      KAFKA_URL: kafka:9093
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      location-service:
        condition: service_healthy
      history-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  geofence-service:
    build:
      context: .
      args:
        SERVICE_NAME: geofence-service
    image: geofence-service:latest
    container_name: beacon-geofence-service
    ports:
      - "8087:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      DB_URL: jdbc:postgresql://geofence-db:5432/geofence_db
      KAFKA_URL: kafka:9093
      GRPC_USER_CHANNEL_URL: user-service:9090
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      location-service:
        condition: service_healthy
      geofence-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  notification-service:
    build:
      context: .
      args:
        SERVICE_NAME: notification-service
    image: notification-service:latest
    container_name: beacon-notification-service
    ports:
      - "8088:8080"
    environment:
      JAVA_OPTS:
      SERVER_PORT: 8080
      EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
      DB_URL: jdbc:postgresql://notification-db:5432/notification_db
      KAFKA_URL: kafka:9093
      GRPC_USER_CHANNEL_URL: user-service:9090
      GRPC_AUTH_CHANNEL_URL: auth-service:9090
    depends_on:
      service-registry:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      geofence-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      notification-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    profiles: [ services ]
    healthcheck: *spring-healthcheck

  # Databases & Caching
  user-db:
    image: neo4j
    container_name: beacon-user-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-beacon_user_db}
    volumes:
      - neo4j_data:/data
    profiles: [ deps ]
    healthcheck: *neo4j-healthcheck
  
  history-db:
    image: timescale/timescaledb-ha:pg17
    container_name: beacon-history-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=history_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_history_db}
    volumes:
      - postgres_history_data:/pgdata
      - ./docker/history/init:/docker-entrypoint-initdb.d
    profiles: [ deps ]
    healthcheck: *pg-healthcheck

  geofence-db:
    image: nickblah/postgis
    container_name: beacon-geofence-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=geofence_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_geofence_db}
    volumes:
      - postgres_geofence_data:/pgdata
      - ./docker/geofence/init:/docker-entrypoint-initdb.d
    profiles: [ deps ]
    healthcheck: *pg-healthcheck
  
  notification-db:
    image: postgres
    container_name: beacon-notification-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_notification_db}
    volumes:
      - postgres_notification_data:/pgdata
      - ./docker/notification/init:/docker-entrypoint-initdb.d
    profiles: [ deps ]
    healthcheck: *pg-healthcheck
  
  location-redis:
    image: redis
    container_name: beacon-location-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PROTECTED_MODE=yes
    volumes:
      - location_redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    profiles: [ deps ]
    healthcheck: *redis-healthcheck
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  map-redis:
    image: redis
    container_name: beacon-map-redis
    ports:
      - "6380:6379"
    volumes:
      - map_redis_data:/data
    profiles: [ deps ]
    healthcheck: *redis-healthcheck

  # Event Brokers
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: beacon-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    profiles: [ deps ]
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=HOST://localhost:9092,DOCKER://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_BROKER_ID=1
      - CLUSTER_ID=EmptNWtoR4GGWx-BH6nGLQ
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    healthcheck:
      test: [ "CMD", "bash", "-c", "cub kafka-ready -b localhost:9092 1 20" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  
  # Orchestration
  prometheus:
    image: prom/prometheus
    container_name: beacon-prometheus
    ports:
      - "9191:9090"
    volumes:
      - ./docker/prometheus/prometheus.${DEPLOY_MODE:-docker}.yml:/etc/prometheus/prometheus.yml:ro
    environment:
      GATEWAY_SERVICE_HOST: 'api-gateway:8080'
      AUTH_SERVICE_HOST: 'auth-service:8080'
      LOCATION_SERVICE_HOST: 'location-service:8080'
      USER_SERVICE_HOST: 'user-service:8080'
      HISTORY_SERVICE_HOST: 'history-service:8080'
      REGISTRY_SERVICE_HOST: 'service-registry:8080'
    
    profiles: [ orchestration ]
  grafana:
    image: grafana/grafana
    container_name: beacon-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    profiles: [ orchestration ]
  loki:
    image: grafana/loki:latest
    container_name: beacon-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./docker/loki/config.yml:/etc/loki/local-config.yml
      - loki-data:/loki
    profiles: [ orchestration ]

volumes:
  neo4j_data:
  postgres_history_data:
  postgres_geofence_data:
  postgres_notification_data:
  location_redis_data:
  map_redis_data:
  grafana-data:
  loki-data:
  kafka_data:
    driver: local