services:
  # Main Services
  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    image: api-gateway:latest
    container_name: beacon-api-gateway
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: ""

  service-registry:
    build:
      context: .
      args:
        SERVICE_NAME: service-registry
    image: service-registry:latest
    container_name: beacon-service-registry
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS: ""

  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    image: auth-service:latest
    container_name: beacon-auth-service
    ports:
      - "8082:8080"
    environment:
      JAVA_OPTS: ""
  
  location-service:
    build:
      context: .
      args:
        SERVICE_NAME: location-service
    image: location-service:latest
    container_name: beacon-location-service
    ports:
      - "8083:8080"
    environment:
      JAVA_OPTS: ""
  
  map-service:
    build:
      context: .
      args:
        SERVICE_NAME: map-service
    image: map-service:latest
    container_name: beacon-map-service
    ports:
      - "8084:8080"
    environment:
      JAVA_OPTS: ""
  
  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    image: user-service:latest
    container_name: beacon-user-service
    ports:
      - "8085:8080"
    environment:
      JAVA_OPTS: ""

  history-service:
    build:
      context: .
      args:
        SERVICE_NAME: history-service
    image: history-service:latest
    container_name: beacon-history-service
    ports:
      - "8086:8080"
    environment:
      JAVA_OPTS: ""

  geofence-service:
    build:
      context: .
      args:
        SERVICE_NAME: geofence-service
    image: geofence-service:latest
    container_name: beacon-geofence-service
    ports:
      - "8087:8080"
    environment:
      JAVA_OPTS: ""

  notification-service:
    build:
      context: .
      args:
        SERVICE_NAME: notification-service
    image: notification-service:latest
    container_name: beacon-notification-service
    ports:
      - "8088:8080"
    environment:
      JAVA_OPTS: ""
  
  # Databases & Caching
  user-db:
    image: neo4j
    container_name: beacon-user-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-beacon_user_db}
    volumes:
      - neo4j_data:/data
  history-db:
    image: timescale/timescaledb-ha:pg17
    container_name: beacon-history-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_history_db}
    volumes:
      - postgres_history_data:/pgdata
      - ./docker/history/init:/docker-entrypoint-initdb.d
  geofence-db:
    image: nickblah/postgis
    container_name: beacon-geofence-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=geofence_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_geofence_db}
    volumes:
      - postgres_geofence_data:/pgdata
      - ./docker/geofence/init:/docker-entrypoint-initdb.d
  notification-db:
    image: postgres
    container_name: beacon-notification-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-beacon_notification_db}
    volumes:
      - postgres_notification_data:/pgdata
      - ./docker/notification/init:/docker-entrypoint-initdb.d
  location-redis:
    image: redis
    container_name: beacon-location-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PROTECTED_MODE=yes
    volumes:
      - location_redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  map-redis:
    image: redis
    container_name: beacon-map-redis
    ports:
      - "6380:6379"
    volumes:
      - map_redis_data:/data

  # Event Brokers
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: beacon-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - CLUSTER_ID=EmptNWtoR4GGWx-BH6nGLQ
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  # Orchestration
  prometheus:
    image: prom/prometheus
    container_name: beacon-prometheus
    ports:
      - "9191:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles: [ orchestration ]
  grafana:
    image: grafana/grafana
    container_name: beacon-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    profiles: [ orchestration ]
  loki:
    image: grafana/loki:latest
    container_name: beacon-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./docker/loki/config.yml:/etc/loki/local-config.yml
      - loki-data:/loki
    profiles: [ orchestration ]

volumes:
  neo4j_data:
  postgres_history_data:
  postgres_geofence_data:
  postgres_notification_data:
  location_redis_data:
  map_redis_data:
  grafana-data:
  loki-data:
  kafka_data:
    driver: local