services:
  prometheus:
    image: prom/prometheus
    container_name: beacon-prometheus
    ports:
      - "9191:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: beacon-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  
  loki:
    image: grafana/loki:latest
    container_name: beacon-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./docker/loki/config.yml:/etc/loki/local-config.yml
      - loki-data:/loki

volumes:
  grafana-data:
  loki-data: