global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'auth-service'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]

  - job_name: 'location-service'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]

  - job_name: 'user-service'
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]

  - job_name: 'history-service'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]

  - job_name: 'service-registry'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]