global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'api-gateway:9292' ]

  - job_name: 'auth-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'auth-service:8080' ]

  - job_name: 'location-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'location-service:8080' ]

  - job_name: 'user-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'user-service:8080' ]

  - job_name: 'history-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'history-service:8080' ]

  - job_name: 'map-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'map-service:8080' ]

  - job_name: 'geofence-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'geofence-service:8080' ]

  - job_name: 'notification-service'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'notification-service:8080' ]

  - job_name: 'service-registry'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'service-registry:8761' ]